-- PokeEdge 管理者向けアクセス集計テーブル
-- Supabase SQL Editorで一度だけ実行してください。
create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page text not null,
  event_name text not null,
  session_key text,
  user_key text,
  logged_in boolean not null default false,
  meta jsonb not null default '{}'::jsonb
);

alter table public.site_analytics_events enable row level security;

drop policy if exists "analytics_insert_anyone" on public.site_analytics_events;
drop policy if exists "analytics_select_anyone" on public.site_analytics_events;

create policy "analytics_insert_anyone"
  on public.site_analytics_events
  for insert
  to anon, authenticated
  with check (true);

create policy "analytics_select_anyone"
  on public.site_analytics_events
  for select
  to anon, authenticated
  using (true);

create index if not exists site_analytics_events_created_at_idx on public.site_analytics_events(created_at desc);
create index if not exists site_analytics_events_page_idx on public.site_analytics_events(page);
create index if not exists site_analytics_events_event_idx on public.site_analytics_events(event_name);
create index if not exists site_analytics_events_user_key_idx on public.site_analytics_events(user_key);


-- 念のため、anon/authenticated ロールに権限を付与します。
grant insert, select on public.site_analytics_events to anon, authenticated;
grant usage, select on sequence public.site_analytics_events_id_seq to anon, authenticated;
